### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by carreb** [carreb/skytracker#1]
In no particular order:
- [ ] Add trackers for every collection and maybe skill exp
- [ ] Add extra options to make trackers more customizable
- [ ] Add OBS Stream Overlay for trackers
- [ ] Refactor
- [ ] Add goals and display time to reach goals in the tracker
- [ ] Add session timeout if idle too long
- [ ] Save finished tracking sessions to view later, download as CSV, and compare to current session
